name: Submit a new site
description: Add a new website to the Ohio directory

body:
  - type: input
    id: url
    attributes:
      label: URL
      description: The main url of the resource
      placeholder: "https://example.com"
    validations:
      required: true

  - type: input
    id: url_type
    attributes:
      label: URL Type
      description: url, rss, atom, activitypub, or atproto
      placeholder: "url"
    validations:
      required: true

  - type: input
    id: category
    attributes:
      label: Category
      description: List of comma-separated tags (e.g., Government, Festival)
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: As precise as possible

  - type: input
    id: alt_location
    attributes:
      label: Alternate Location
      description: Central Ohio, NE Ohio, SW Ohio, SE Ohio, NW Ohio
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link
      description: The homepage of the resource, e.g. if url=https://columbus.gov/feed/ then link=https://columbus.gov/
    validations:
      required: true
