name: Handle New Site Submissions

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 python-slugify

      - name: Run script to update CSV and generate files
        run: |
          python .github/scripts/process_issue.py "${{ github.event.issue.body }}"
      
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          branch_name="auto/add-site-issue-${{ github.event.issue.number }}"
          git checkout -b $branch_name
          git add ohio.csv output.json feeds.opml
          git commit -m "Add site from issue #${{ github.event.issue.number }}"
          git push origin $branch_name

      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: auto/add-site-issue-${{ github.event.issue.number }}
          title: "Add site from issue #${{ github.event.issue.number }}"
          body: "This pull request adds a new site based on the submitted issue."
