name: Handle New Site Submissions

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 python-slugify feedparser

      - name: Run script to update CSV and generate files
        run: python .github/scripts/process_issue.py "${{ github.event.issue.body }}"

      - name: Check for modified files
        run: |
          git status
          git diff --stat

      - name: Stage changes
        run: git add ohio.csv ohio.json ohio.opml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Add site from issue #${{ github.event.issue.number }}"
          title: "Add new site"
          body: "This pull request adds a new site. Closes #${{ github.event.issue.number }}"
          branch: auto/add-site-issue-${{ github.event.issue.number }}
          base: main
          delete-branch: true

